import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Dominik Orincsai</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Dominik Orincsai</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div>
            <h2>Dominik Orincsai</h2>
            <h3>Developer and Cybersecurity Enthusiast</h3>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui amet
              quia expedita distinctio nesciunt molestias odit vel voluptates,
              consectetur itaque cumque repellat cum sit accusantium inventore
              quasi quaerat architecto sunt.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
